### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by wesleycoder** [Blrrt/cordova-plugin-speech-recognition-ios-browser-polyfill#1]
This doesn't install anymore nor via `npm`, `yarn` nor with `cordova plugin add`.
Is this still being maintened? Are there any alternatives?

**Comment by psirenny** [comment]
This isn't a cordova plugin. It seems like it's still available on npm:

```
npm info @blrrt/cordova-plugin-speech-recognition-ios-browser-polyfill
```

**Comment by wesleycoder** [comment]
Oh, thanks,

I was trying to install this polyfill as `cordova-plugin-speech-recognition-ios-browser-polyfill` instead of `@blrrt/cordova-plugin-speech-recognition-ios-browser-polyfill`
It was silly of my part not searching npm first, sorry.
